### PR TITLE
Add == operator override

### PR DESCRIPTION
**Pull request by AlexandreAndrade00**
Hello. My objective with this PR is to implement operator ==. I used the method compareTo().

### CODE REVIEW

**Comment by goeo1066** [comment]
@AlexandreAndrade00 Thank you for the contribution :)

**Comment by AlexandreAndrade00** [comment]
No problem :grin: Can you bump the version and publish to pub.dev?

**Comment by goeo1066** [comment]
@AlexandreAndrade00 
Version was bumped to 0.0.5 :)
https://pub.dev/packages/tsid_dart

**Comment by AlexandreAndrade00** [comment]
Thank you a lot! :grin:

**Pull request merged**
